baseURL = "https://nicogreu.github.io/"
languageCode = "en-us"
#title = "Nicolas Greliche site"
metaDataFormat = "yaml"
theme = "blist"


DefaultContentLanguage = "en"
DefaultContentLanguageInSubdir = true
[languages]
  [languages.en]
    contentDir = "content/en" #English
    weight = 1
    languageName = "English"
    [languages.en.params]
      introTitle = "Nicolas Greliche"
      introAlias = "alias greu & duduq"
      introJobs = "Statistician, Independent Researcher, Artist"
      introPhoto = "/Me tweaked.jpg"
      logo = "/logo3.png"

    [[languages.en.menu.main]]
        name = ""
        url = "/journey"
        weight = 1

    [[languages.en.menu.main]]
        name = "Watercolor paintings"
        url = "/watercolor"
        weight = 2

  [languages.fr]
    contentDir = "content/fr" #French
    weight = 1
    languageName = "Francais"
    [languages.fr.params]
      introTitle = "Nicolas Greliche"
      introAlias = "alias greu & duduq"
      introJobs = "Statisticien, Chercheur indépendant, Artiste"
      introPhoto = "/Me tweaked.jpg"
      logo = "/logo3.png"

    [[languages.fr.menu.main]]
        name = ""
        url = "/journey"
        weight = 1


[params]

  custom_css = ["custom.css"]

  # Enable the darkmode toggle in header
  darkModeToggle = false
  
  # Enable search in header
  enableSearch = false

  # Option to customize the search parameters of a page
  # Below are the supported options; Note that including entire content
  # may slowdown the loading of search results
  # Title of page is included by default
  searchKeys = [
    "tags",
    "date",
    "categories",
    "summary",
    "content",
    "link",
    "author"
  ]

  # Custom copyright - optional
  copyright = "Copyright © 2021 - Nicolas Greliche · All rights reserved"
  favicon = "/favicon_black.svg"

  # Color for the intro details and social links block, not applicable for dark mode
  # Supported values: Any color from TailwindCSS default colors
  # Reference: https://tailwindcss.com/docs/customizing-colors
  ascentColor = "bg-gray-900"

  # The page bundle that is shown on the front page
  frontBundle = "project"

  # Used to hide the post metadata such as posted date, reading time and word count
  # Can be used at site level or page level
  hideMeta = false

  # To hide "Other languages" option if the post is available in multiple languages
  # Can be used at site level or page level
  hideOtherLanguages = false

  # Add support for Table of contents
  # Can be added to a page level also in markdown frontmatter
  toc = false

  # Hides the thumbnail in post view
  # Thumbnails in home and blog pages will still be shown
  # This setting can also be in page's markdown file
  hidePageThumbnail = false

# Comments system
[params.comments]
  # Supports disqus, giscus and utterances
  # Check hugo docs for setting up disqus
  system = "giscus"

  # Options for giscus, exclude hyphens
  repo = ""
  repoid = ""
  category = ""
  categoryid = ""
  mapping = ""
  strict = ""
  reactionsenabled = ""
  emitmetadata = ""
  inputposition = ""
  theme = ""

  # Options for utterances, exclude hyphens
  # repo = ""
  # issueterm = ""
  # theme = ""

[params.homepage.social]
  # Global params common for both languages
  title = "Follow me"
  description = "I work on everything coding and tweet developer memes"


  [[params.homepage.social.icons]]
    website = "instagram"
    url = "https://www.instagram.com/duduqdrawstuff/"
  [[params.homepage.social.icons]]
    website = "whatsapp"
    url = "https://wa.me/33684211454"
  [[params.homepage.social.icons]]
    website = "mastodon"
    url = "https://mastodon.social/@nicogreu"
  [[params.homepage.social.icons]]
    website = "linkedin"
    url = "https://linkedin.com/in/nicolas-greliche/"
  [[params.homepage.social.icons]]
    website = "googlescholar"
    url = "https://scholar.google.es/citations?user=XDIgmMMAAAAJ/"
  [[params.homepage.social.icons]]
    website = "github"
    url = "https://github.com/nicogreu/"
  [[params.homepage.social.icons]]
    website = "orcid"
    url = "https://orcid.org/0000-0003-0683-2257"
  [[params.homepage.social.icons]]
    website = "buymeacoffee"
    url = "https://www.buymeacoffee.com/nicogreu/"
  [[params.homepage.social.icons]]
    website = "twitter"
    url = "https://twitter.com/"
  [[params.homepage.social.icons]]
    website = "xing"
    url = "https://www.xing.com/profile/"
  [[params.homepage.social.icons]]
    website = "telegram"
    url = "https://t.me/"
  [[params.homepage.social.icons]]
    website = "medium"
    url = "https://medium.com/"
  [[params.homepage.social.icons]]
    website = "reddit"
    url = "https://reddit.com/"
  [[params.homepage.social.icons]]
    website = "dribbble"
    url = "https://dribbble.com/"
  [[params.homepage.social.icons]]
    website = "stackoverflow"
    url = "https://stackoverflow.com/"
  [[params.homepage.social.icons]]
    website = "xda"
    url = "https://forum.xda-developers.com/"
  [[params.homepage.social.icons]]
    website = "tiktok"
    url = "https://tiktok.com"
  [[params.homepage.social.icons]]
    website = "youtube"
    url = "https://youtube.com"
  [[params.homepage.social.icons]]
    website = "facebook"
    url = "https://facebook.com"
  [[params.homepage.social.icons]]
    website = "behance"
    url = "https://behance.net"

[[menu.main]]
  name = "About"
  url = "/about"

[build]
  writeStats = true

[outputs]
  home = ["HTML", "RSS", "JSON"]

# syntax highlight settings
[markup]
  [markup.highlight]
    style = "dracula"
  [markup.goldmark.renderer]
    # Enable to include inline HTML
    unsafe = true
